spring:
  application:
    name: api-receitas
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/api}
    username: ${DATABASE_USERNAME:api}
    password: ${DATABASE_PASSWORD:api123321}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: receitas
  jpa:
    properties:
      hibernate:
        default_schema: receitas

management:
  endpoints:
    web:
      base-path: /receitas/actuator
      exposure:
        include: [ 'prometheus' ]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}