spring:
  application:
    name: api-receitas
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:Post123321}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: receita ### add component here

  jpa:
    properties:
      hibernate:
        default_schema: receita

management:
  endpoints:
    web:
      base-path: /receitas/actuator
      exposure:
        include: [ 'prometheus' ]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${DISCOVERY_HOST}:8761/eureka/

springdoc:
  api-docs:
    path: /receitas/v3/api-docs
  swagger-ui:
    path: /receitas/swagger-ui
