apiVersion: apps/v1
kind: Deployment
metadata:
  name: receitas
spec:
  selector:
    matchLabels:
      app: receitas
  replicas: 1
  template:
    metadata:
      labels:
        app: receitas
    spec:
      containers:
        - name: receitas
          image: pasilva2023/receitas:latest
          ports:
            - containerPort: 8080
          env:

            - name: DISCOVERY_HOST
              valueFrom:
                configMapKeyRef:
                  name: discovery-configmap
                  key: DISCOVERY_HOST

            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_HOST

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,info,prometheus"
          volumeMounts:
            - name: config-volume
              mountPath: "/config"
      volumes:
        - name: config-volume
          configMap:
            name: receitas-circuit-breaker-config