apiVersion: v1
kind: Service
metadata:
  name: receitas
  labels:
    name: receitas
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: receitas